### ISSUE TITLE
Remove deprecated scripts

### ISSUE THREAD

**Issue by matthewfeickert** [thaler-lab/Wasserstein#30]
Now that PR #24 is in [`scripts/install-libomp-macos.sh`](https://github.com/thaler-lab/Wasserstein/blob/7063f2ffd6a72cf71535eca35841ac185164dfea/scripts/install-libomp-macos.sh) is no longer needed and should be removed.

**Comment by j-s-ashley** [comment]
I ought to have done that in #24, apologies!
