### ISSUE TITLE
Move tests out of package directory

### ISSUE THREAD

**Issue by matthewfeickert** [thaler-lab/Wasserstein#33]
The tests currently live under `wasserstein/tests/` (https://github.com/thaler-lab/Wasserstein/tree/7063f2ffd6a72cf71535eca35841ac185164dfea/wasserstein/tests) meaning that they get packaged, even into the wheel. This isn't a useful practice, and the `wasserstein/tests/` directory should get moved to a top level `tests/` directory.

cc @j-s-ashley

**Comment by j-s-ashley** [comment]
Moving the tests directory without making further changes causes CI to fail for at least two Linux builds (using [Python 3.10](https://github.com/thaler-lab/Wasserstein/actions/runs/9644875399/job/26597901013?pr=34#step:8:18) and [Python 3.11](https://github.com/thaler-lab/Wasserstein/actions/runs/9644875399/job/26597901230?pr=34#step:8:18)).

**Comment by j-s-ashley** [comment]
> Moving the tests directory without making further changes causes CI to fail for ~at least two Linux jobs (using [Python 3.10](https://github.com/thaler-lab/Wasserstein/actions/runs/9644875399/job/26597901013?pr=34#step:8:18) and [Python 3.11](https://github.com/thaler-lab/Wasserstein/actions/runs/9644875399/job/26597901230?pr=34#step:8:18))~ [all jobs](https://github.com/j-s-ashley/Wasserstein/actions/runs/9648148480).

Resolved thanks to [Matthew's smarts](https://github.com/thaler-lab/Wasserstein/pull/34#issuecomment-2187030487) by changing the target of `pytest` from `wasserstein` to the `tests` directory here:
https://github.com/thaler-lab/Wasserstein/blob/b3d12162fe04fa5b7452a1f8bc76754de899b4fe/.github/workflows/ci.yml#L81
