### ISSUE TITLE
ci: Test using pre-release state of EnergyFlow repo

### ISSUE THREAD

**Issue by j-s-ashley** [thaler-lab/Wasserstein#46]
To summarize @matthewfeickert in https://github.com/thaler-lab/EnergyFlow/pull/41#issuecomment-2192177572, 

- [x] For now, the EnergyFlow installation at line 72 of ci.yml https://github.com/thaler-lab/Wasserstein/blob/ad6d815d2f4483528d4039c954d23bbb286ae220/.github/workflows/ci.yml#L72 can be changed to 
```
python -m pip uninstall --yes EnergyFlow
python -m pip install "git+https://github.com/thaler-lab/EnergyFlow.git"
```

- [ ] The release of fixes for EnergyFlow and full macOS support in Wasserstein will allow the entire `Install dependencies` step to be removed. https://github.com/thaler-lab/Wasserstein/blob/ad6d815d2f4483528d4039c954d23bbb286ae220/.github/workflows/ci.yml#L69

**Comment by matthewfeickert** [comment]
To give some context on where to go from here, once a new release of EnergyFlow has been made to PyPI then

https://github.com/thaler-lab/Wasserstein/blob/444905b415e84de30d903f949b21e464919ecd3d/.github/workflows/ci.yml#L79-L81

can get replace with just a new lower bound.
