### ISSUE TITLE
Update build to use `scikit-build-core` instead of `setuptools`

### ISSUE THREAD

**Issue by j-s-ashley** [thaler-lab/Wasserstein#51]
To support packaging and CI/CD modernization in line with [Scientific Python Best Practices](https://learn.scientific-python.org/development/guides/packaging-compiled/), the `scikit-build-core` build backend should be used instead of `setuptools`.

**Comment by j-s-ashley** [comment]
Progress on the [working branch for this issue](https://github.com/j-s-ashley/Wasserstein/tree/build/skbc) is currently hindered by two (likely related somehow) errors:

1. [`ubuntu-latest`](https://github.com/j-s-ashley/Wasserstein/actions/runs/9725277354/job/26842396172#step:5:336) and [`macos-13`](https://github.com/j-s-ashley/Wasserstein/actions/runs/9725277354/job/26842396257#step:5:256) fail while building with Ninja
2. [`windows-latest`](https://github.com/j-s-ashley/Wasserstein/actions/runs/9725277354/job/26842396220#step:5:241) fails while building with Visual Studio

According to the workflow logs, the Ubuntu and MacOS builds fail to locate Python.h and the Windows build can't find any of the [`wasserstein/internal/`](https://github.com/thaler-lab/Wasserstein/tree/master/wasserstein/internal) files.

**Comment by j-s-ashley** [comment]
Build attempts currently [fail](https://github.com/j-s-ashley/Wasserstein/actions/runs/9820120950/job/27114361372?pr=5#step:6:137) on all platforms with the following error:
```
/home/runner/work/Wasserstein/Wasserstein/wasserstein/wasserstein.cpp:179:11: fatal error: Python.h: No such file or directory
        179 | # include <Python.h>
            |           ^~~~~~~~~~
      compilation terminated.
```
This build uses `find_package` to find Python in [CMakeLists.txt](https://github.com/j-s-ashley/Wasserstein/pull/5/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR18).

**Comment by j-s-ashley** [comment]
> Build attempts currently [fail](https://github.com/j-s-ashley/Wasserstein/actions/runs/9820120950/job/27114361372?pr=5#step:6:137) on all platforms

This was resolved by [explicitly include the Python library directory](https://github.com/j-s-ashley/Wasserstein/pull/5/commits/287940c8fafec34e180f21e1c5c4afbbeecf58bd#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR23). This ended up also being necessary for the NumPy directory. Solving these resulted in a further [error](https://github.com/j-s-ashley/Wasserstein/actions/runs/9874870917/job/27270221746#step:5:482): the workflow cannot locate the contents of `wasserstein/internal/`.

**Comment by j-s-ashley** [comment]
> with the following error:
> 
> ```
> /home/runner/work/Wasserstein/Wasserstein/wasserstein/wasserstein.cpp:179:11: fatal error: Python.h: No such file or directory
>         179 | # include <Python.h>
>             |           ^~~~~~~~~~
>       compilation terminated.
> ```
This was resolved by [explicitly include the Python library directory](https://github.com/j-s-ashley/Wasserstein/pull/5/commits/287940c8fafec34e180f21e1c5c4afbbeecf58bd#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR23). This ended up also being necessary for the NumPy directory. Solving these resulted in a further [error](https://github.com/j-s-ashley/Wasserstein/actions/runs/9874870917/job/27270221746#step:5:482): the workflow cannot locate the contents of wasserstein/internal/.

**Comment by j-s-ashley** [comment]
> > Build attempts currently [fail](https://github.com/j-s-ashley/Wasserstein/actions/runs/9820120950/job/27114361372?pr=5#step:6:137) on all platforms with the following error:
> > ```
> > /home/runner/work/Wasserstein/Wasserstein/wasserstein/wasserstein.cpp:179:11: fatal error: Python.h: No such file or directory
> >         179 | # include <Python.h>
> >             |           ^~~~~~~~~~
> >       compilation terminated.
> > ```
> 
> This was resolved by [explicitly including the Python library directory](https://github.com/j-s-ashley/Wasserstein/pull/5/commits/287940c8fafec34e180f21e1c5c4afbbeecf58bd#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR23). This ended up also being necessary for the NumPy directory. Solving these resulted in a further [error](https://github.com/j-s-ashley/Wasserstein/actions/runs/9874870917/job/27270221746#step:5:482): the workflow cannot locate the contents of `wasserstein/internal/`.

As discovered by @henryiii, all of these problems spawned from overlooking the fact that [wasserstein.cpp](https://github.com/thaler-lab/Wasserstein/blob/master/wasserstein/wasserstein.cpp) is the SWIG **output file**.

**Comment by j-s-ashley** [comment]
New problem: 

https://github.com/j-s-ashley/Wasserstein/pull/5#issuecomment-2226217673
> We are not renaming to _wasserstein_omp.

**Comment by henryiii** [comment]
The problem is the current version makes the following structure:

```
wasserstein/wasserstein.py
wasserstein/_wasserstein.py
wasserstein/_wasserstein_omp.so
```

This requires modifying the `_wasserstein.cpp` file so that the custom `_wasserstein.py` can sit in-between the SWIG produced wrapper Python file and the SWIG produced `.so` file.

We can avoid this messy modification by installing into a subdirectory:

```
wasserstein/wasserstein.py
wasserstein/_wasserstein.py
wasserstein/omp/_wasserstein.so
```

**Comment by j-s-ashley** [comment]
Installing into the `wasserstein/omp/` subdirectory allows most tests to pass, but `macos-13` fails with an `ImportError` as noted [here](https://github.com/j-s-ashley/Wasserstein/pull/5#issuecomment-2258738312).

**Comment by j-s-ashley** [comment]
> Installing into the `wasserstein/omp/` subdirectory allows most tests to pass, but `macos-13` fails with an `ImportError` as noted [here](https://github.com/j-s-ashley/Wasserstein/pull/5#issuecomment-2258738312).

This error is also present on `macos-latest` after merging PR #48.

**Comment by j-s-ashley** [comment]
> > Installing into the `wasserstein/omp/` subdirectory allows most tests to pass, but `macos-13` fails with an `ImportError` as noted [here](https://github.com/j-s-ashley/Wasserstein/pull/5#issuecomment-2258738312).
> 
> This [error](https://github.com/j-s-ashley/Wasserstein/actions/runs/10182179977/job/28164059794?pr=5) is also present on `macos-latest` after merging PR #48, but rather than resulting from a `Symbol not found: ___kmpc_barrier` error (as occurs with `macos-13`), `macos-latest` throws a `no LC_RPATH's found` error.
> 
> Full error (one of many)

@henryiii @matthewfeickert, could this be related to why the following lines were needed in [setup.py](https://github.com/thaler-lab/Wasserstein/blob/master/setup.py#L71C4-L75C49)?

```
if platform.system() == 'Darwin':
        omp_cxxflags.insert(0, '-Xpreprocessor')
        libs = ['omp']
        ldflags = ['-Wl,-rpath,/usr/local/lib', '-L/opt/homebrew/lib', '-Wl,-rpath,/opt/homebrew/lib']
        includes.append('/opt/homebrew/include')
```

**Comment by matthewfeickert** [comment]
> could this be related to why the following lines were needed in [setup.py](https://github.com/thaler-lab/Wasserstein/blob/master/setup.py#L71C4-L75C49)?
> 
> ```
> if platform.system() == 'Darwin':
>         omp_cxxflags.insert(0, '-Xpreprocessor')
>         libs = ['omp']
>         ldflags = ['-Wl,-rpath,/usr/local/lib', '-L/opt/homebrew/lib', '-Wl,-rpath,/opt/homebrew/lib']
>         includes.append('/opt/homebrew/include')
> ```

Ah good point @j-s-ashley. Reposting things that we discussed on our call, as you had to explicitly add these pieces of information in PR #48 to get things to build properly, and PR #48 was using `setuptools` and `setup.py` then you were explicitly adding in this logic to the Python code getting executed. Now that has been removed and I think(?) we need to do as you suggested here and communicate to `scikit-build-core` that same information in the tool configuration section in `pyproject.toml`.

Off the top of my head I don't know how to do that, so I think you'll need to poke in the `scikit-build-core` docs first and then ask @henryiii and me if things aren't clear there.

**Comment by henryiii** [comment]
This is already being added by FindOpenMP's `OpenMP::OpenMP_CXX` target. If you look at the verbose build log, you can see `-Xclang -fopenmp` when building and `-Wl,-rpath,/usr/local/lib  /usr/local/lib/libomp.dylib` when linking.

**Comment by matthewfeickert** [comment]
...and @henryiii has the fix here: https://github.com/j-s-ashley/Wasserstein/pull/5#issuecomment-2274221318

**Comment by matthewfeickert** [comment]
Okay now that @j-s-ashley has https://github.com/j-s-ashley/Wasserstein/pull/5 working targeting their fork, if a similar/same PR is made targeting https://github.com/thaler-lab/Wasserstein then this Issue can get addressed.

(While I know you can change the target branch on a PR I don't know if you can change the target repository too, so that's why I'm suggesting a new PR and not just editing the existing one's target. Could try though.)
